### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by westor7** [aspircd/aspIRCd#15]
Hello,

I tried to check the docs and test this ircd but seems the website (https://aspircd.com) is down..

any docs link ?

- Thanks!

**Comment by thecodezero** [comment]
Hi @westor7 , this is not an issue regarding the IRCd , kindly hit us down at irc.aspircd.com Port 6667/+6697 #lounge / #aspircd-support for more information regarding the IRCd, we are upright and ready to help you with it

**Comment by Syzolin** [comment]
Hi, @westor7 its back! (But still under development)

**Comment by Syzolin** [comment]
Closing it.
