### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by TwinUsers** [aspircd/aspIRCd#19]
/bin/bash ../libtool --silent  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include -I. -I../include       -g -O2 -Wall -MT mbedtls.lo -MD -MP -MF .deps/mbedtls.Tpo -c -o mbedtls.lo mbedtls.c
mbedtls.c:45:35: fatal error: mbedtls_embedded_data.h: No such file or directory
compilation terminated.
Makefile:491: recipe for target 'mbedtls.lo' failed
make[3]: *** [mbedtls.lo] Error 1

**Comment by Syzolin** [comment]
Posting the error won’t work, explaining the situation is the key to the problem you are facing , by the way what OS are you trying to build and who doesn’t like to opt for openssl for god sake in this world of IRC!

**Comment by TwinUsers** [comment]
openSSL also don't display fingerprints. Will this effect people logging in to services with fingerprint?

**Comment by Syzolin** [comment]
no it will not

**Comment by Syzolin** [comment]
Will solve in 5.1.1

**Comment by syzolin** [comment]
Project opened for solving this issue in the release/5.1 branch
