### ISSUE TITLE
modes

### ISSUE THREAD

**Issue by bogdomania** [aspircd/aspIRCd#40]
the **/quote help cmodes** lists all the available modes w/o params. Some of them are not working.
 P: is an unknown mode char to me              (to make the channel permanent)
 S: is an unknown mode char to me              (only SSL/TLS users may join)
 O: is an unknown mode char to me
 A: is an unknown mode char to me

+y works, for IRCops
 For users, returns a "You need to be a channel operator in #ChannelName to do that.", even if I'm @ or not.

L.E. :
cmodes available, are CDFIMQRTXabcefghijklmnopqrstuvy bkloveqjfI
This means that the help file is not updated?

**Comment by PegasusHD** [comment]
Hi @bogdomania , 

It looks like we haven't updated the Help File and along with that there are a few channel modes I'm aware of that are broken to some extent.

The fix to those issues will be resolved in 4.0.3 (Branch: dev/asp403)
